# Generated by Django 2.0 on 2018-06-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField()),
                ('token', models.TextField()),
                ('tenant', models.CharField(max_length=128)),
                ('resource', models.URLField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
