# Generated by Django 2.0 on 2017-12-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.URLField(max_length=256)),
                ('tenant', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
