# Generated by Django 2.0 on 2017-12-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
